language: go
go:
  - "1.14.x"

services:
  - docker

env:
  global:
    - GO111MODULE=on

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - echo 'skip install'

script:
  - echo 'skip script'

after_success:
  - docker --version
  - docker build -f docker/Dockerfile.opera --label "commit=$TRAVIS_COMMIT" -t kybernetwork/go-opera:$TRAVIS_COMMIT .

deploy:
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      all_branches: true
